# Generated by Django 4.1.7 on 2023-03-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пары')),
                ('type', models.CharField(choices=[('1', 'Лекция'), ('2', 'Практика'), ('3', 'Лабораторная')], max_length=20, verbose_name='Тип пары')),
                ('teacher', models.CharField(max_length=200, verbose_name='Препод')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=50, verbose_name='День недели')),
                ('parity', models.CharField(choices=[('0', 'Четная неделя'), ('1', 'Нечетная неделя')], max_length=200, verbose_name='Четность дня недели')),
                ('fifth_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_lesson', to='models.lesson', verbose_name='Пятая пара')),
                ('first_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_lesson', to='models.lesson', verbose_name='Первая пара')),
                ('fourth_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_lesson', to='models.lesson', verbose_name='Четвертая пара')),
                ('second_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_lesson', to='models.lesson', verbose_name='Вторая пара')),
                ('third_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_lesson', to='models.lesson', verbose_name='Третья пара')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
    ]
