# Generated by Django 4.1.7 on 2023-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.CharField(default=0, max_length=200, verbose_name='Корпус-аудитория'),
            preserve_default=False,
        ),
    ]
